Add req.method to passed tags
RueLaLa/node-connect-datadog pull request #4
Opened 2018-02-27 20:35 UTC by nsheaps

Adds tracking for req.method to connect-datadog middleware that gets passed to statsd.histogram

2018-02-27 20:42 UTC, rue-dhurd commented on lib/index.test.js
> +          expectConnectedToDatadog(stat, statTags)
Not your fault, but I don't like how this method reads. Took me a minute to realize this was us asserting the method tag wasn't used. I think I may take that on in a followup PR 😉

2018-02-27 20:42 UTC, rue-dhurd approved these changes

2018-02-28 14:49 UTC, rue-mchang commented on lib/index.js
>  			if (response_code) {
If you look up like 10 lines, this case is actually already being handled. We're just weren't _explicitly_ accepting `options.method` at the top. I like explicitly accepting `method` at the top, and I think we can just modify what's already there a few lines up to take `method` instead of `options.method`.

2018-02-28 14:49 UTC, rue-mchang requested changes
There's some redundancy since `req.method` would get pushed to tags twice now.

2018-02-28 14:52 UTC, rue-dhurd commented on lib/index.js
>  			if (response_code) {
If we don't have a use case for toggling it on and off, I don't think we should put in the option. This work was to add the method to the tag, so if it's already there 🎉 .

2018-02-28 19:36 UTC, rue-mchang approved these changes

2018-03-01 14:32 UTC, merged